In [45]:
import textract
import os
import pickle
from pathlib import Path
import numpy as np
import random
import pandas as pd
from itertools import combinations
root = Path(".")


In [46]:
my_path = root / "Pickled_files" / "Incident_Matrix"
dbfile = open(my_path, 'rb')     
incident_matrix = pickle.load(dbfile)
dbfile.close()

my_path = root / "Pickled_files" / "Shingle_id"
dbfile = open(my_path, 'rb')     
shingle_id = pickle.load(dbfile)
dbfile.close()

my_path = root / "Pickled_files" / "Shingles"
dbfile = open(my_path, 'rb')     
shingles = pickle.load(dbfile)
dbfile.close()

In [47]:
# list of all doc names
files = list()
for dir in [r"\Auto", r"\Property"]:
    cur_dir = r".\Docs" + dir
    for file in os.listdir(cur_dir):
        cur_path = r".\Docs" + dir + "\\" + file
        files.append(cur_path)
files.sort()

In [48]:
# List of string with entire documents 
documents = list()

for file in files:
    cur = textract.process(file).decode("utf8")
    
    ans = list()
    for i in range(len(cur)):
        if cur[i].isalnum():
            ans.append(cur[i].lower())
        else:
            ans.append(' ')
    
    res = list()
    for i in range(len(ans) - 1):
        if ans[i] == ans[i + 1] and ans[i] == ' ':
            continue
        else:
            res.append(ans[i])
    
    if len(ans) > 0:
        res.append(ans[-1])
        documents.append(''.join(res))

In [49]:
def get_hash_functions(cnt_hsh , mod = 423212) : 
    hash_function = list()
    for i in range(cnt_hsh) : 
        a = random.randint(1 , 100)
        b = random.randint(1 , 100)
        hash_function.append((a , b , mod))
    return hash_function

In [50]:
hash_functions = get_hash_functions(50 , len(incident_matrix))
hash_functions

[(65, 69, 21106),
 (80, 97, 21106),
 (43, 81, 21106),
 (30, 6, 21106),
 (73, 32, 21106),
 (75, 93, 21106),
 (78, 87, 21106),
 (57, 71, 21106),
 (23, 29, 21106),
 (2, 53, 21106),
 (68, 20, 21106),
 (23, 54, 21106),
 (37, 71, 21106),
 (83, 70, 21106),
 (35, 74, 21106),
 (33, 38, 21106),
 (67, 85, 21106),
 (64, 28, 21106),
 (19, 24, 21106),
 (44, 6, 21106),
 (58, 48, 21106),
 (68, 98, 21106),
 (44, 85, 21106),
 (5, 78, 21106),
 (80, 20, 21106),
 (50, 93, 21106),
 (63, 22, 21106),
 (10, 40, 21106),
 (88, 87, 21106),
 (62, 31, 21106),
 (82, 47, 21106),
 (51, 11, 21106),
 (3, 79, 21106),
 (43, 98, 21106),
 (6, 56, 21106),
 (65, 42, 21106),
 (58, 5, 21106),
 (81, 79, 21106),
 (96, 74, 21106),
 (83, 97, 21106),
 (64, 43, 21106),
 (22, 100, 21106),
 (18, 73, 21106),
 (88, 24, 21106),
 (25, 40, 21106),
 (27, 50, 21106),
 (76, 32, 21106),
 (90, 9, 21106),
 (59, 79, 21106),
 (89, 2, 21106)]

In [51]:
signature_matrix = np.zeros(shape=(len(hash_functions), len(documents)))
signature_matrix.fill(10 ** 18)
signature_matrix

array([[1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1

In [52]:
for shingle_row in range(len(incident_matrix)) : 
    cur_hsh = 0
    for (a , b , mod) in hash_functions : 
        hsh_value = ((shingle_row + 1) * a + b) % mod
        shingle_row_val = incident_matrix[shingle_row]
        for doc_id in range(len(shingle_row_val)) : 
            if shingle_row_val[doc_id] == 1 : 
                signature_matrix[cur_hsh][doc_id] = min(signature_matrix[cur_hsh][doc_id] , hsh_value)
        cur_hsh += 1

In [53]:
print(signature_matrix)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  0.  0.]
 [ 1.  1.  5.  5.  5.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 3.  4.  4.  5.  6.  6.  0.  6.  6.  2.  3.  2.  1.  3.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 4.  2.  6.  7.  0.  7.  0.  0.  7.  0.  1.  1.  0.  3.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  2.  0.  2.  0.  2.  2.  3.  2.  1.  2.  1.  3.  2.]
 [ 2.  2.  2.  4.  2.  2.  0.  2.  2.  1.  2.  1.  2.  2.]
 [ 7.  7.  5.  1.  5.  5.  1.  1.  1.  1.  5.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  0.  0.  0.  0.  2.  0.  0.  2.]
 [ 1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  1.]
 [ 3.  3.  3.  3.  1.  1.  2.  3.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  2.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  2

In [54]:
my_path = root / "Pickled_files" / "Signature_Matrix"
dbfile = open(my_path, 'wb')
pickle.dump(signature_matrix, dbfile) 
dbfile.close()

In [55]:
def get_candidate_pairs(b , r) : 
    candidate_pairs = set()
    cur_band_start , cur_band_end = 0 , r - 1
    for bands in range(b) :
        band_signature = dict() 
        for doc_id in range(len(documents)) : 
            matrix = tuple(signature_matrix[cur_band_start : cur_band_end + 1 , doc_id])
            if band_signature.get(matrix) == None : 
                band_signature[matrix] = [doc_id]
            else : 
                band_signature[matrix].append(doc_id)
        for docs in band_signature.items() : 
            if len(docs[1]) > 1 : 
                c_pairs = list(combinations(docs[1] , 2))
                for (a , b) in c_pairs : 
                    candidate_pairs.add((min(a , b) , max(a , b)))
        cur_band_end += r
        cur_band_start += r
    return candidate_pairs

In [56]:
candidate_pairs = get_candidate_pairs(10 , 5)

In [57]:
candidate_pairs

{(0, 1),
 (0, 9),
 (0, 10),
 (1, 5),
 (1, 9),
 (2, 4),
 (2, 5),
 (3, 6),
 (3, 10),
 (3, 12),
 (4, 5),
 (5, 7),
 (6, 7),
 (6, 10),
 (7, 8),
 (7, 9),
 (7, 12),
 (8, 9),
 (8, 12),
 (9, 10),
 (9, 11),
 (10, 11),
 (11, 12),
 (12, 13)}

In [58]:
def get_similar_documents(threshold , signature_matrix) : 
    similar_docs = set()
    col_size = len(signature_matrix)
    for doc1 in range(len(documents)) : 
        for doc2 in range(doc1 + 1 , len(documents)) : 
            matrix1 = list(signature_matrix[0:col_size , doc1])
            matrix2 = list(signature_matrix[0:col_size , doc2])
            similarity = jaccard_similarity(matrix1 , matrix2)
            print(similarity)
            if similarity >= threshold : 
                similar_docs.add((a , b , similarity))

In [59]:
def jaccard_similarity(a , b) :
    intersection = len(list(set(a).intersection(b)))
    union = (len(a) + len(b)) - intersection
    return float(intersection) / union

In [60]:
similar_docs = get_similar_documents(0.5 , signature_matrix)

0.08695652173913043
0.08695652173913043
0.0989010989010989
0.08695652173913043
0.0989010989010989
0.05263157894736842
0.05263157894736842
0.06382978723404255
0.06382978723404255
0.06382978723404255
0.05263157894736842
0.05263157894736842
0.07526881720430108
0.08695652173913043
0.08695652173913043
0.07526881720430108
0.0989010989010989
0.05263157894736842
0.05263157894736842
0.05263157894736842
0.06382978723404255
0.05263157894736842
0.05263157894736842
0.05263157894736842
0.07526881720430108
0.08695652173913043
0.07526881720430108
0.08695652173913043
0.05263157894736842
0.05263157894736842
0.05263157894736842
0.06382978723404255
0.05263157894736842
0.05263157894736842
0.05263157894736842
0.07526881720430108
0.0989010989010989
0.0989010989010989
0.06382978723404255
0.06382978723404255
0.07526881720430108
0.06382978723404255
0.06382978723404255
0.05263157894736842
0.06382978723404255
0.07526881720430108
0.0989010989010989
0.05263157894736842
0.06382978723404255
0.06382978723404255
0.0638