In [1]:
import textract
import os
import pickle
from pathlib import Path
import numpy as np
import random
import pandas as pd
from itertools import combinations
root = Path(".")


In [2]:
my_path = root / "Pickled_files" / "Incident_Matrix"
dbfile = open(my_path, 'rb')     
incident_matrix = pickle.load(dbfile)
dbfile.close()

my_path = root / "Pickled_files" / "Shingle_id"
dbfile = open(my_path, 'rb')     
shingle_id = pickle.load(dbfile)
dbfile.close()

my_path = root / "Pickled_files" / "Shingles"
dbfile = open(my_path, 'rb')     
shingles = pickle.load(dbfile)
dbfile.close()

In [3]:
# list of all doc names
files = list()
for dir in [r"\Auto", r"\Property"]:
    cur_dir = r".\Docs" + dir
    for file in os.listdir(cur_dir):
        cur_path = r".\Docs" + dir + "\\" + file
        files.append(cur_path)
files.sort()

In [4]:
# List of string with entire documents 
documents = list()

for file in files:
    cur = textract.process(file).decode("utf8")
    
    ans = list()
    for i in range(len(cur)):
        if cur[i].isalnum():
            ans.append(cur[i].lower())
        else:
            ans.append(' ')
    
    res = list()
    for i in range(len(ans) - 1):
        if ans[i] == ans[i + 1] and ans[i] == ' ':
            continue
        else:
            res.append(ans[i])
    
    if len(ans) > 0:
        res.append(ans[-1])
        documents.append(''.join(res))

In [5]:
def get_hash_functions(cnt_hsh , mod = 423212) : 
    hash_function = list()
    for i in range(cnt_hsh) : 
        a = random.randint(1 , 100)
        b = random.randint(1 , 100)
        hash_function.append((a , b , mod))
    return hash_function

In [6]:
hash_functions = get_hash_functions(50 , len(incident_matrix))
hash_functions

[(36, 23, 21106),
 (51, 50, 21106),
 (25, 84, 21106),
 (65, 16, 21106),
 (55, 5, 21106),
 (7, 76, 21106),
 (79, 57, 21106),
 (6, 82, 21106),
 (91, 81, 21106),
 (31, 79, 21106),
 (65, 32, 21106),
 (52, 63, 21106),
 (94, 59, 21106),
 (59, 53, 21106),
 (50, 32, 21106),
 (9, 62, 21106),
 (62, 36, 21106),
 (74, 61, 21106),
 (98, 99, 21106),
 (42, 6, 21106),
 (17, 12, 21106),
 (58, 51, 21106),
 (2, 70, 21106),
 (36, 22, 21106),
 (8, 8, 21106),
 (17, 51, 21106),
 (82, 72, 21106),
 (69, 90, 21106),
 (98, 28, 21106),
 (81, 12, 21106),
 (90, 50, 21106),
 (89, 45, 21106),
 (20, 17, 21106),
 (42, 53, 21106),
 (46, 62, 21106),
 (54, 31, 21106),
 (97, 99, 21106),
 (1, 81, 21106),
 (6, 17, 21106),
 (87, 78, 21106),
 (35, 35, 21106),
 (47, 41, 21106),
 (27, 89, 21106),
 (71, 64, 21106),
 (16, 76, 21106),
 (55, 14, 21106),
 (16, 13, 21106),
 (50, 24, 21106),
 (12, 40, 21106),
 (98, 86, 21106)]

In [7]:
signature_matrix = np.zeros(shape=(len(hash_functions), len(documents)))
signature_matrix.fill(10 ** 18)
signature_matrix

array([[1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18],
       [1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18, 1.e+18,
        1.e+18, 1.e+18, 1

In [8]:
for shingle_row in range(len(incident_matrix)) : 
    cur_hsh = 0
    for (a , b , mod) in hash_functions : 
        hsh_value = ((shingle_row + 1) * a + b) % mod
        shingle_row_val = incident_matrix[shingle_row]
        for doc_id in range(len(shingle_row_val)) : 
            if shingle_row_val[doc_id] == 1 : 
                signature_matrix[cur_hsh][doc_id] = min(signature_matrix[cur_hsh][doc_id] , hsh_value)
        cur_hsh += 1

In [9]:
print(signature_matrix)

[[ 1.  5.  1.  3.  1.  1.  3.  1.  3.  3.  3.  1.  1.  3.]
 [ 5.  3.  0.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [10. 11. 10.  2.  8. 10.  8.  2.  2.  1.  0.  1.  0.  0.]
 [ 2.  4.  4.  0.  4.  4.  0.  1.  2.  0.  1.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 3.  3.  6.  1.  3.  3.  0.  0.  3.  0.  0.  0.  0.  3.]
 [ 1.  1.  2.  1.  2.  1.  2.  1.  1.  0.  1.  0.  1.  0.]
 [ 1.  0.  1.  1.  1.  1.  1.  2.  4.  3.  2.  2.  3.  3.]
 [ 3.  3.  1.  3.  3.  3.  1.  1.  1.  1.  3.  1.  3.  3.]
 [ 1.  1.  5.  1.  5.  5.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

In [10]:
my_path = root / "Pickled_files" / "Signature_Matrix"
dbfile = open(my_path, 'wb')
pickle.dump(signature_matrix, dbfile) 
dbfile.close()

In [11]:
def get_candidate_pairs(b , r) : 
    candidate_pairs = set()
    cur_band_start , cur_band_end = 0 , r - 1
    for bands in range(b) :
        band_signature = dict() 
        for doc_id in range(len(documents)) : 
            matrix = tuple(signature_matrix[cur_band_start : cur_band_end + 1 , doc_id])
            if band_signature.get(matrix) == None : 
                band_signature[matrix] = [doc_id]
            else : 
                band_signature[matrix].append(doc_id)
        for docs in band_signature.items() : 
            if len(docs[1]) > 1 : 
                c_pairs = list(combinations(docs[1] , 2))
                for (a , b) in c_pairs : 
                    candidate_pairs.add((min(a , b) , max(a , b)))
        cur_band_end += r
        cur_band_start += r
    return candidate_pairs

In [12]:
candidate_pairs = get_candidate_pairs(10 , 5)

In [13]:
candidate_pairs

{(0, 3),
 (0, 6),
 (0, 9),
 (0, 12),
 (1, 3),
 (1, 5),
 (2, 4),
 (2, 5),
 (3, 4),
 (3, 5),
 (3, 8),
 (3, 9),
 (3, 11),
 (3, 13),
 (4, 5),
 (6, 9),
 (6, 12),
 (7, 8),
 (7, 9),
 (7, 10),
 (7, 11),
 (7, 12),
 (7, 13),
 (8, 9),
 (8, 10),
 (8, 11),
 (8, 12),
 (8, 13),
 (9, 10),
 (9, 11),
 (9, 12),
 (9, 13),
 (10, 11),
 (10, 12),
 (10, 13),
 (11, 12),
 (11, 13),
 (12, 13)}

In [61]:
def get_similar_documents(threshold) : 
    similar_docs = set()
    col_size = len(incident_matrix)
    for doc1 in range(len(documents)) : 
        for doc2 in range(doc1 + 1 , len(documents)) : 
            matrix1 = incident_matrix[0:col_size , doc1]
            matrix2 = incident_matrix[0:col_size , doc2]
            matrix1 , matrix2 = matrix1.astype(int) , matrix2.astype(int)
            similarity = jaccard_similarity(matrix1 , matrix2)
            print(similarity)
            if similarity >= threshold : 
                similar_docs.add((doc1 , doc2 , similarity))

In [62]:
def jaccard_similarity(a , b) :
    bits = (a & b)
    return float(np.count_nonzero(bits == 1) / len(a)) 

In [63]:
similar_docs = get_similar_documents(0.5)
print(similar_docs)

0.2398843930635838
0.2211219558419407
0.20885056382071449
0.20648156922202218
0.20264379797214063
0.2639059982943239
0.278356865346347
0.267885909220127
0.3012413531697148
0.29167061499099783
0.29896711835497014
0.2866009665497963
0.2875485643892732
0.20780820619728987
0.19837960769449445
0.20093812186108215
0.199753624561736
0.23367762721500995
0.2392684544679238
0.23235099023974226
0.25575665687482235
0.24964465081019616
0.2559461764427177
0.24846015351085
0.24921823178243155
0.18842983037998673
0.1944470766606652
0.1888088695157775
0.2230645314128684
0.22353833033260684
0.21681038567232067
0.23543068321804225
0.22960295650525916
0.23490950440632996
0.22827631952999147
0.228418459205913
0.18658201459300672
0.18970908746328058
0.22282763195299915
0.22443854828010992
0.21804226286364067
0.2337250071069838
0.22931867715341608
0.23315644840329763
0.23021889510091917
0.22652326352695915
0.21406235193783757
0.21188287690704066
0.20984554155216525
0.20216999905240216
0.22173789443760067
0.2